### ISSUE TITLE
Make the Study Tracker reusable 

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue#34]
Ability to reuse the Study Tracker in other projects:

- [x] As a first step, cloning the existing repository and deleting what is not needed for the specific project
- [x] Define colours in a separate file and remove the use of hardcoded colours, e.g #FFFFFF or rgb(0,0,0,0)
- [x] Find out how to override styles in a AG-Grid styles in React app
- [ ] Have an input JSON schema that is standardised - is this a metaschema?
- [ ] Define a plan to have a Development and Production Environments
